---
## (Linux-mandrake 7.0 Russian Edition) ; ALT Linux ;
- name: "Ensure OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  apt_rpm:
    pkg: "java-1.{{ ojdk_version }}.0-openjdk-devel"
    state: "{{ ojdk_state }}"
    update_cache: "{{ 'yes' if ojdk_state in ['present','latest'] else 'no' }}"
