---
## (ClearOS) ; Clear Linux OS (CLOS) / ClearOS System ; Linux Mix
# @ https://www.clearos.com/clearfoundation/development/clearos/content:en_us:dev_packaging_clearos_7.x_start
# @ https://tepette.wordpress.com/2014/03/22/clearos-install-latest-openjdk/
- name: "Ensure OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  yum:
    name: "java-{{ '1.' if ojdk_version|int < 9 }}{{ ojdk_version }}{{ '.0' if ojdk_version|int < 9 }}-openjdk-devel"
    state: "{{ ojdk_state }}"
    update_cache: "{{ 'yes' if ojdk_state in ['present','latest'] else 'no' }}"
    validate_certs: "{{ 'yes' if ojdk_gpg_uncheck else 'no' }}"
    enablerepo: "clearos-core"
    # disablerepo: "epel,ol7_latest"
