---
## (ClearOS) ; Clear Linux OS (CLOS) / ClearOS System ; Linux Mix
#@ https://www.clearos.com/clearfoundation/development/clearos/content:en_us:dev_packaging_clearos_7.x_start
#@ https://tepette.wordpress.com/2014/03/22/clearos-install-latest-openjdk/
- name: "Ensure OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  yum:
    name: "java-{% if ojdk_version|int < 9 %}1.{{ ojdk_version }}.0{% else %}{{ ojdk_version }}{% endif %}-openjdk-devel"
    state: "{{ ojdk_state }}"
    update_cache: "{% if ojdk_state in ['present','latest'] %}yes{% else %}no{% endif %}"
    validate_certs: "{% if ojdk_gpg_uncheck %}yes{% else %}no{% endif %}"
    enablerepo: "clearos-core"
    #disablerepo: "epel,ol7_latest"
