---
## (HP-UX) ;
#@ https://knowledgebase.progress.com/articles/Article/P27223
#@ https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=HPUXJDKJRE80
#@ https://community.hpe.com/t5/Languages-and-Scripting/Java-10-support-for-HPUX/td-p/7011422
- name: "Ensure OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  swdepot:
    name: "openjdk{{ ojdk_version }}"
    state: "{{ ojdk_state }}"
    depot: "{{ ojdk_repository }}"
  when:
    - "ojdk_repository is defined"
    - "ojdk_repository|length"
- import_tasks: 'na.yml'
  when: "(ojdk_repository is not defined) or (not ojdk_repository|length)"
