---
## (Mandriva (Mandrake)) ;  AbulÉdu ; Annvix ; APODIO ; Caixa Mágica ; Castle Linux ; EduLinux ; édutice ; Mageia ; MCNLive ; OpenMandriva Lx ; PCLinux OS ; ROSA linux ; Turkix ; Unity Linux
- name: "Ensure OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  urpmi:
    name: "java-{{ '1.' if ojdk_version|int < 9 }}{{ ojdk_version }}{{ '.0' if ojdk_version|int < 9 }}-openjdk-devel"
    state: "{{ ojdk_state }}"
    update_cache: "{{ 'yes' if ojdk_state in ['present','latest'] else 'no' }}"
