---
## (Red Hat Linux) ; Amazon (OVS) ; Aurox ; CentOS ; CloudLinux OS ; Fedora ; Fermi Linux ; Linux XP ; Open vSwitch (OVS) ; Oracle Linux (OEL) ; Parallels Server Bare metal (PSBM / Virtuozzo / Parallels Cloud Server) ; Qubes OS ; Red Hat Entreprise Linux (RHEL) ; Rocks Cluster Distribution ; Scientific Linux (SL) ; Scientific Linux CERN (SLC) ; Xen Server
- name: "Ensure Alternative Repository is Present"
  yum_repository:
    description: "OpenJDK {{ ojdk_version }}"
    name: "openjdk{{ ojdk_version }}"
    file: "openjdk"
    baseurl: "{{ ojdk_repository }}"
    state: "{{ ojdk_state }}"
    enabled: yes
    # enabled: "{{ 'yes' if ojdk_state in ['present','latest'] else 'no' }}"
    gpgcheck: "{{ 'no' if ojdk_gpg_uncheck else 'yes' }}"
    ssl_check_cert_permissions: "{{ 'no' if ojdk_gpg_uncheck else 'yes' }}"
  when: "ojdk_repository is defined"
- name: "Ensure OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  # backend: auto, yum (aka yum3/YUM3/yum-deprecated), yum4 (YUM4), dnf
  yum:
    name: "java-{{ '1.' if ojdk_version|int < 9 }}{{ ojdk_version }}{{ '.0'if ojdk_version|int < 9 }}-openjdk-devel"
    state: "{{ ojdk_state }}"
    update_cache: "{{ 'yes' if ojdk_state in ['present','latest'] else 'no' }}"
    validate_certs: "{{ 'yes' if ojdk_gpg_uncheck else 'no' }}"
    # enablerepo: "ojdk_repository"
