---
## (SunOS) ; Dyson ; EON ZFS Storage ; illumos ; MartUX ; MilaX ; Jaris OS ; napp-it ; Nexenta OS ; NexentaStor ; OpenIndiana ; OmniOS ; OpenSolaris ; OpenSXCE ; Oracle Solaris ; SchiliX ; SmartOS ; StormOS ; Trusted Solaris ;
- name: "Ensure OpenJDK {{ ojdk_version }} SVR4 package is {{ ojdk_state | capitalize }}"
  svr4pkg:
    name: "openjdk{{ ojdk_version }}"
    state: "{{ ojdk_state }}"
    src: "{{ ojdk_repository }}"
  when:
    - "ansible_distribution_major_version|int < 11"
    - "ojdk_repository is defined"
    - "ojdk_repository|length"
- name: "Ensure via CSW that OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  pkgutil:
    name: "jdk-{{ ojdk_version }}"
    state: "{{ ojdk_state }}"
    site: "{{ ojdk_repository }}"
    update_catalog: "{{ 'yes' if ojdk_state in ['present','latest'] else 'no' }}"
  when:
    - "ansible_distribution_major_version|int > 10"
    - "ojdk_repository is defined"
    - "ojdk_repository|length"
# @ https://marc.info/?l=openbsd-ports&m=120959254931322
- import_tasks: 'na.yml'
  when: "(ojdk_repository is not defined) or (not ojdk_repository|length)"
- name: "Ensure OpenJDK {{ ojdk_version }} IPS package is {{ ojdk_state | capitalize }}"
  pkg5:
    # @ https://bugs.openjdk.java.net/browse/JDK-8153043
    # @ https://bugs.openjdk.java.net/browse/JDK-8152786
    # @ https://bugs.openjdk.java.net/browse/JDK-8216065
    name: "developer/java/jdk-{{ ojdk_version }}"
    state: "{{ ojdk_state }}"
    accept_licenses: yes
  when: "ansible_distribution_major_version|int > 10"
