---
## (SuSE Linux Profesional (SuSE)) ; OpenSuSE ; SuSE Linux Entreprise Desktop (SLED) ; SuSE Linux Entreprise Server (SLES) ;
- name: "Ensure OpenJDK {{ ojdk_version }} is {{ ojdk_state | capitalize }}"
  zypper:
    name: "java-{% if ojdk_version|int < 9 %}1_{{ ojdk_version }}_0{% else %}{{ ojdk_version }}{% endif %}-openjdk-devel"
    state: "{{ ojdk_state }}"
    update_cache: "{% if ojdk_state in ['present','latest'] %}yes{% else %}no{% endif %}"
    disable_gpg_check: "{{ ojdk_gpg_uncheck }}"
